language: php

dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

services:
  - mysql

env:
  - DB=mysql DB_USER=root

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer self-update
  - wget https://phar.phpunit.de/phpunit-5.7.phar -O phpunit.phar

before_script:
  # MySQL
  - mysql < "$TRAVIS_BUILD_DIR/test/reset_database.sql"

  # Composer
  - composer install --prefer-source

  - ./test/reset_tests.sh

script: php phpunit.phar

matrix:
  allow_failures:
    - php: nightly
