language: php

dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

services:
  - mysql

env:
  - DB=mysql DB_USER=root

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer self-update
  - wget https://phar.phpunit.de/phpunit-5.7.phar -O phpunit.phar

before_script:
  # MySQL
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'SET FOREIGN_KEY_CHECKS = 0; DROP DATABASE IF EXISTS test; DROP SCHEMA IF EXISTS second_hand_books; DROP SCHEMA IF EXISTS contest; DROP DATABASE IF EXISTS reverse_bookstore; DROP SCHEMA IF EXISTS bookstore_schemas; SET FOREIGN_KEY_CHECKS = 1;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE test; CREATE SCHEMA bookstore_schemas; CREATE SCHEMA contest; CREATE SCHEMA second_hand_books; CREATE DATABASE reverse_bookstore;'; fi"

  # Composer
  - composer install --prefer-source

  - ./test/reset_tests.sh

script: ./phpunit.phar

matrix:
  allow_failures:
    - php: nightly
