language: php

dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

services:
  - mysql

env:
  - DB=mysql DB_USER=root

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer self-update

before_script:
  # MySQL
  - cat "$TRAVIS_BUILD_DIR/test/etc/mysql.cnf" | sudo tee -a /etc/mysql/my.cnf
  - sudo service mysql restart
  - mysql < "$TRAVIS_BUILD_DIR/test/reset_database.sql"

  # Composer
  - composer install --prefer-source

  - ./test/reset_tests.sh

script: php vendor/bin/phpunit

matrix:
  allow_failures:
    - php: nightly
